# Generated by Django 5.2.2 on 2025-09-26 20:41

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_images',
            fields=[
                ('image_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=core.models.gallery_image_upload_path)),
                ('caption', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_actions.admin')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
