# Generated by Django 5.2.2 on 2025-09-26 22:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_images',
            name='image_id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
