# Generated by Django 5.2.2 on 2025-09-26 20:41

import blogs.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('like_count', models.IntegerField(default=0)),
                ('title', models.CharField(default='Untitled Blog', max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=15)),
                ('comment_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=blogs.models.blog_image_upload_path)),
                ('admin_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_actions.admin')),
            ],
        ),
    ]
