# Generated by Django 5.2.2 on 2025-06-17 11:34

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_like_count_blog_user_id_alter_blog_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='media_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.blog_image_upload_path),
        ),
    ]
