# Generated by Django 5.2.2 on 2025-06-17 15:01

import blogs.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_media_id_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=blogs.models.blog_image_upload_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Untitled Blog', max_length=200),
        ),
    ]
