# Generated by Django 5.2.2 on 2025-06-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_comment_id_alter_blog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
