# Generated by Django 5.2.2 on 2025-07-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like_id',
        ),
    ]
