# Generated by Django 5.2.2 on 2025-06-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_articles',
            name='description',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
