# Generated by Django 5.2.2 on 2025-06-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_research_articles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_articles',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
