# Generated by Django 5.2.2 on 2025-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
