# Generated by Django 5.2.2 on 2025-09-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='line_total',
        ),
    ]
