# Generated by Django 5.2.2 on 2025-09-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_cartitem_line_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
