# Generated by Django 5.2.2 on 2025-09-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
