# Generated by Django 5.2.2 on 2025-09-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_cart_id_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='user_id',
        ),
    ]
