# Generated by Django 5.2.2 on 2025-09-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_cart_id_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
